# Configuration for daily arxiv paper aggregation
# Customize keywords and settings below

keywords:
  "AI Agents":
    filters:
      - "AI agent"
      - "artificial intelligence agent"
      - "autonomous agent"
      - "intelligent agent"
      - "multi-agent"
      - "agent-based"
  
  "Large Language Models":
    filters:
      - "large language model"
      - "LLM"
      - "language model"
      - "transformer"
      - "GPT"
      - "BERT"
      - "ChatGPT"
      
  "Computer Vision":
    filters:
      - "computer vision"
      - "image recognition"
      - "object detection"
      - "semantic segmentation"
      - "visual transformer"
      - "CNN"
      
  "Machine Learning":
    filters:
      - "machine learning"
      - "deep learning"
      - "neural network"
      - "reinforcement learning"
      - "federated learning"
      - "transfer learning"

# Search settings
max_results: 10

# Publishing settings
publish_readme: true
publish_gitpage: false
publish_wechat: false
show_badge: true

# File paths
json_readme_path: "README.json"
md_readme_path: "README.md"
json_gitpage_path: "docs/index.json"
md_gitpage_path: "docs/index.md"
json_wechat_path: "docs/wechat.json"
md_wechat_path: "docs/wechat.md"

# Update settings
update_paper_links: false